export const inputs = [
    {
      label:"Nombre",
      type: "text",
      name: "name",
      placeholder: "Escribe tu nombre",
      //value:`${form.name}`,
      required: true,
      //error: `${errors.name}`,
      error: "name",
    },
    {
      label:"E-mail",
      type: "email",
      name: "email",
      placeholder: "Escribe tu email",
      //value:`${form.email}`,
      required: true,
      //error: `${errors.email}`,
      error: "email",
    },
    {
      label:"Asunto",
      type: "text",
      name: "subject",
      placeholder: "Escribe el asunto",
      //value: `${form.subject}`,
      required: true,
      //error: `${errors.subject}`,
      error: "subject",
    },
    {
      label: "Comentarios",
      type: "text",
      name: "comments",
      placeholder: "Escribe tus comentarios",
      //value: `${form.subject}`,
      required: true,
      cols:"50",
      rows:"5",
      //error: `${errors.subject}`,
      error: "subject",
    },
    {
      label: "Acepto terminos y condiciones",
      type: "checkbox",
      name: "terms",
      required: true,
    }
  ];
  